feat: Add support for PackageType in JSON serverless template
aws/aws-lambda-dotnet pull request #1004
Opened 2021-11-30 20:17 UTC by 96malhar

*Issue #, if available:*
DOTNET-5528

*Description of changes:*
feat: Add support for PackageType in JSON serverless template

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-12-08 18:26 UTC, normj requested changes

2021-12-09 20:59 UTC, 96malhar commented on Libraries/src/Amazon.Lambda.Annotations.SourceGenerator/Models/LambdaFunctionModel.cs
> +        /// The default value is set to Zip for dev-preview
Fixed

2021-12-09 20:59 UTC, 96malhar commented on Libraries/src/Amazon.Lambda.Annotations.SourceGenerator/Writers/CloudFormationJsonWriter.cs
>              _jsonWriter.SetToken($"{propertiesPath}.Handler", lambdaFunction.Handler);
Fixed

2021-12-09 20:59 UTC, 96malhar commented on Libraries/src/Amazon.Lambda.Annotations/LambdaFunctionAttribute.cs
> +        /// The deployment package type of the Lambda function. The supported values are Zip or Image.
Fixed

2021-12-09 20:59 UTC, 96malhar commented on Libraries/test/Amazon.Lambda.Annotations.SourceGenerators.Tests/WriterTests/CloudFormationJsonWriterTests.cs
> +            Assert.Equal("Zip", propertiesToken["PackageType"]);
Done

2021-12-09 20:59 UTC, 96malhar commented on Libraries/test/Amazon.Lambda.Annotations.SourceGenerators.Tests/WriterTests/CloudFormationJsonWriterTests.cs
> +            Assert.Null(propertiesToken["Handler"]);
Done

2021-12-09 21:13 UTC, normj approved these changes

2021-12-09 21:20 UTC, merged