Corrected property name ConnectionAt to ConnectedAt in APIGatewayProxyRequest.ProxyRequestContext class.
aws/aws-lambda-dotnet pull request #1145
Opened 2022-04-15 21:50 UTC by ashishdhingra

*Issue #, if available:* #1140

*Description of changes:*
Corrected property name ConnectionAt to ConnectedAt in APIGatewayProxyRequest.ProxyRequestContext class.

*NOTE:* There is no test case for this request, and also there is no sample request event available in Lambda documentation for WebProxy integration. This is a breaking change, hence change log needs to be updated accordingly post-release.
___
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-04-16 00:07 UTC, normj requested changes
Can you make sure there is a unit test that covers this property?

2022-04-18 17:54 UTC, ashishdhingra commented
> Can you make sure there is a unit test that covers this property?

@normj I have added a new test case with the actual JSON generated for WebSocket API Connect request (took some cue from https://www.freecodecamp.org/news/real-time-applications-using-websockets-with-aws-api-gateway-and-lambda-a5bb493e9452/ to set it up and log JSON to CloudWatch logs). Please review.

**NOTE:** Existing test case for proxy request doesn't fit to WebSocket scenario.

2022-04-18 17:57 UTC, normj approved these changes

2022-04-18 18:27 UTC, ganeshnj approved these changes

2022-04-18 19:01 UTC, merged