remove S3 SDK deps
aws/aws-lambda-dotnet pull request #1237
Opened 2022-07-08 17:47 UTC by jcstorms1

*Issue #, if available:*
#1226 
*Description of changes:*

- Updates `S3Event.cs` to handle all properties correctly
- Removes SDK.S3 dependency 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-07-12 23:26 UTC, normj requested changes

2022-07-21 13:43 UTC, jcstorms1 commented
Friendly bump @normj or @ashovlin if you don't mind taking a look at the changes 🙇 
cc @ashishdhingra

2022-07-21 21:35 UTC, normj approved these changes
I have pulled down the branch locally and confirm the existing S3 serialization test work. This will be a major version bump but user's migrating should have to do very little to switch. Most likely change a using statement.

2022-07-22 00:01 UTC, boblodgett approved these changes

2022-08-02 16:33 UTC, merged

2022-08-02 22:20 UTC, normj commented
The PR has been released in version 3.0.0 of the Amazon.Lambda.S3 package. Thank you for your work on this PR!