Fix issue of syncing CF template when all LambdaFunctions are removed.
aws/aws-lambda-dotnet pull request #1258
Opened 2022-07-31 07:55 UTC by normj

*Description of changes:*
Fix an issue when all of the remaining `LambdaFunction` are removed from the project the CF template is not synced leaving the Lambda functions defined in the template.

The fix has the following changes:
* Move the computation of the project directory. It used to be computed from the first `LambdaFunction` but since there might not be any `LambdaFunction` it was moved to the syntax visitor and where it can be computed on the first class that was found.
* Change the Generator's short circuit from there being no `LambdaFunction` which caused the bug to only short circuit if the project directory was not calculated. That would happen if there are no classes in the project.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-08-01 19:10 UTC, ganeshnj requested changes

2022-08-01 19:10 UTC, ganeshnj commented on Libraries/src/Amazon.Lambda.Annotations.SourceGenerator/CloudFormationTemplateFinder.cs
> +            return File.Exists(templateAbsolutePath);
should use IFileManager wrapper here.
```suggestion
            return _fileManager.Exists(templateAbsolutePath);
```

2022-08-01 20:17 UTC, normj commented on Libraries/src/Amazon.Lambda.Annotations.SourceGenerator/CloudFormationTemplateFinder.cs
> +            return File.Exists(templateAbsolutePath);
Good catch

2022-08-01 20:17 UTC, ganeshnj approved these changes

2022-08-02 13:27 UTC, philasmar approved these changes

2022-08-02 16:33 UTC, merged