fix incorrect type
aws/aws-lambda-dotnet pull request #1523
Opened 2023-06-07 19:47 UTC by jp-grusling

Based on the documentation at https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-verify-auth-challenge-response.html#cognito-user-pools-lambda-trigger-syntax-verify-auth-challenge, the current type is incorrect. This fixes and local testing confirms resolution.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-06-07 20:40 UTC, normj requested changes
Agreed the `ChallengeAnswer` was mismodeled. Could you update this test JSON file https://github.com/aws/aws-lambda-dotnet/blob/ca6614f745879bbb5afea5ea1d1f02cb4685fad0/Libraries/test/EventsTests.Shared/cognito-verifyauthchallenge-event.json#L20 and then this test case https://github.com/aws/aws-lambda-dotnet/blob/ca6614f745879bbb5afea5ea1d1f02cb4685fad0/Libraries/test/EventsTests.Shared/EventTests.cs#L731

2023-06-07 21:08 UTC, normj approved these changes

2023-06-07 21:14 UTC, ashishdhingra approved these changes
LGTM

2023-06-08 23:15 UTC, merged

2023-06-09 05:41 UTC, normj commented
Version 2.1.1 of Amazon.Lambda.CognitoEvents has been released with this PR. Thanks for the fix!