Can register encoding options when adding the service to the service …
aws/aws-lambda-dotnet pull request #1575
Opened 2023-08-31 09:28 UTC by hugohlln

…collection

*Issue 1574*

*Description of changes:*

Can now register content type for transformation by passing options to the HostingOptions object

2023-08-31 13:37 UTC, brignolij commented
Good idea, Very usefull for webp images with api gateway.

2023-09-08 00:19 UTC, normj requested changes
Thanks for the PR. I think the approach to solve the problem of configuring binary data is good. A few minor comments plus we also need some tests in the `Amazon.Lambda.AspNetCoreServer.Test` project.

2023-09-08 00:19 UTC, normj commented on Libraries/src/Amazon.Lambda.AspNetCoreServer.Hosting/HostingOptions.cs
> +    public IEncodingOptions EncodingOptions { get; set; }
`IEncodingOptions` is defined in an `Internal` namespace so it shouldn't be exposed on the public API.

2023-09-08 00:19 UTC, normj commented on Libraries/src/Amazon.Lambda.AspNetCoreServer/Internal/EncodingOptions.cs
> +namespace Amazon.Lambda.AspNetCoreServer.Internal
Seems like the `EncodingOptions` and interface should be in `Amazon.Lambda.AspNetCoreServer.Hosting`. They are basically metadata of the `HostingOptions`.

2023-09-08 00:19 UTC, normj commented on Libraries/src/Amazon.Lambda.AspNetCoreServer/Internal/EncodingOptions.cs
> +    public class EncodingOptions : IEncodingOptions
We need docs on the class and interface.

2023-09-08 00:19 UTC, normj commented on Libraries/src/Amazon.Lambda.AspNetCoreServer.Hosting/HostingOptions.cs
> +    /// The encoding response options used by the Lambda
Can you add a sentence that informs the reader that this is used to adjust what content types have their data sent to API Gateway as binary data?

2023-09-08 09:39 UTC, hugohlln commented
@normj Thanks for your feedbacks

I just dit a new commit with following changes :
- Add comments
- Change the namespace of IEncodingOptions and EncodingOptions

For unit tests, what would be the best way to test the injection of IEncodingOptions ?

2023-09-28 01:58 UTC, CamileDahdah commented on Libraries/src/Amazon.Lambda.AspNetCoreServer.Hosting/Internal/LambdaRuntimeSupportServer.cs
> +                if(encodingOptions != null)
This code block and the one under method APIGatewayRestApiMinimalApi are identical. Can you create a private method and call it from both methods?

2023-09-28 10:03 UTC, hugohlln commented
@CamileDahdah 

I just moved the registration of IEncodingOptions to LambdaRuntimeSupportServer level and removed redundant code from each AbstractAspNetCoreFunction<TREQUEST, TRESPONSE> implementations (APIGatewayHttpApiV2MinimalApi, APIGatewayRestApiMinimalApi and ApplicationLoadBalancerMinimalApi)

2026-03-18 22:54 UTC, normj commented
Closing as this feature was address in PR https://github.com/aws/aws-lambda-dotnet/pull/2267 that exposed all of the extension points from Amazon.Lambda.AspNetCoreServer onto the HostingOptions including `RegisterResponseContentEncodingForContentEncoding`. That PR was released as part of version 1.10.0 of Amazon.Lambda.AspNetCoreServer.Hosting.

@hugohlln I appreciate your effort but it made sense finally address getting all of the extension points over.

2026-03-18 22:54 UTC, closed without merging