chore(deps): bumping Powertools packages
aws/aws-lambda-dotnet pull request #1631
Opened 2023-11-23 05:17 UTC by sliedig

2023-11-24 18:42 UTC, ashishdhingra requested changes
@sliedig Thanks for the PR. Please review if you also need to update [PowertoolsServerless](https://github.com/aws/aws-lambda-dotnet/blob/master/Blueprints/BlueprintDefinitions/vs2022/PowertoolsServerless/template/src/BlueprintBaseName.1/BlueprintBaseName.1.csproj) blueprint as well. Refer https://github.com/aws/aws-lambda-dotnet/pull/1585 as a reference.

2023-11-27 02:54 UTC, sliedig commented
Ooops, thanks. That's done now.

2023-11-27 22:03 UTC, normj commented
In somebodies spare time we should update this code I use to automatically update all of the blueprints to the latest version of the SDK packages and the packages in this repo to also include PowerTools.

https://github.com/aws/aws-lambda-dotnet/blob/master/Blueprints/BlueprintPackager/UpdatePackageReferenceVersions.cs

2023-12-01 17:10 UTC, ashishdhingra approved these changes

2023-12-15 15:23 UTC, merged