Added application/wasm in the dictionary of known content types.
aws/aws-lambda-dotnet pull request #1794
Opened 2024-08-20 18:22 UTC by ashishdhingra

*Issue #, if available:* #1786

*Description of changes:*
Added `application/wasm` in the dictionary of known content types.
___
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-08-20 22:52 UTC, normj approved these changes

2024-08-20 22:53 UTC, normj requested changes
Can you also version bump Amazon.Lambda.AspNetCoreServer.Hosting so it pulls in the new version of Amazon.Lambda.AspNetCoreServer?

2024-08-21 17:06 UTC, ashishdhingra commented
> Can you also version bump Amazon.Lambda.AspNetCoreServer.Hosting so it pulls in the new version of Amazon.Lambda.AspNetCoreServer?

Done

2024-08-21 17:57 UTC, normj approved these changes

2024-08-23 16:48 UTC, dscpinheiro approved these changes

2024-08-23 16:48 UTC, afroz429 approved these changes

2024-08-23 16:50 UTC, merged