Setting HasStarted to true when calling StartAsync
aws/aws-lambda-dotnet pull request #1808
Opened 2024-09-09 04:37 UTC by bozalina

*Description of changes:* 
This fixes a bug when running a gRPC-Web service in Lambda where trailers are not properly written as part of the response payload because the response feature hasn't been marked as started.  The check for `HasStarted` when selecting the trailers destination in gRPC .NET is [here](https://github.com/grpc/grpc-dotnet/blob/master/src/Grpc.AspNetCore.Server/Internal/GrpcProtocolHelpers.cs#L156).

Calling `StartAsync` now marks the response feature as started.  I also added unit tests to check the default value for `HasStarted` and the value after calling `StartAsync`.

Unit tests are passing

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-09-27 14:03 UTC, bhoradc commented
Hi @bozalina, 

Thank you for contributing the PR. Our team will review it and get back to you as soon we can. 

Regards, 
Chaitanya

2025-02-14 07:35 UTC, normj requested changes
Change looks good. Can you add a change file to the PR for release. To do that add a file in `.autover/changes/<random-guid>.json` with the following content.
```
{
  "Projects": [
    {
      "Name": "Amazon.Lambda.AspNetCoreServer",
      "Type": "Patch",
      "ChangelogMessages": [
        "Fixed issue with marking the response body started. This is required for writing trailing headers"
      ]
    },
    {
      "Name": "Amazon.Lambda.AspNetCoreServer.Hosting",
      "Type": "Patch",
      "ChangelogMessages": [
        "Update Amazon.Lambda.AspNetCoreServer dependency to latest."
      ]
    }	
  ]
}
```

2025-02-14 18:16 UTC, normj approved these changes

2025-02-14 18:19 UTC, dscpinheiro approved these changes

2025-02-21 01:07 UTC, merged