add packaging of runtime
aws/aws-lambda-dotnet pull request #1897
Opened 2024-12-05 18:23 UTC by gcbeattyAWS

*Issue #, if available:*

*Description of changes:*

1. Add Amazon.Lambda.RuntimeSupport dll to the output nuget package
3. Add test to verify dll is inside the content folder.

*Testing*
1. So far only tested via checking that the files are in the nuget package manually. I still need to test that this dll works by running with the aspire proof of concept.
![Screenshot 2024-12-04 153915](https://github.com/user-attachments/assets/51ac3b00-6be3-4a63-8a59-ac5d9b195788)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-12-05 18:24 UTC, gcbeattyAWS commented on Tools/LambdaTestTool-v2/src/Amazon.Lambda.TestTool/Amazon.Lambda.TestTool.csproj
> +	  <None Include="$(OutputPath)Amazon.Lambda.RuntimeSupport.dll" Pack="true" PackagePath="content" Visible="false" />
wasnt sure if this needed to be `content` or `lib` folder. was seeing this warning when doing pack command

```
The assembly 'content\Amazon.Lambda.RuntimeSupport.dll' is not inside the 'lib' folder and hence it won't be added as a reference when the package is installed into a project. Move it into the 'lib' folder if it needs to be referenced.
```

but in our case in we are referencing the dll as part of a command line argument in the aspire proof of concept , so not sure if it really matters

2024-12-05 18:24 UTC, gcbeattyAWS commented on Tools/LambdaTestTool-v2/tests/Amazon.Lambda.TestTool.UnitTests/PackagingTests.cs
> +    public void VerifyPackageContentsHasRuntimeSupport()
added this test case but wasnt sure it was overkill or not

2024-12-05 18:25 UTC, gcbeattyAWS commented on Tools/LambdaTestTool-v2/src/Amazon.Lambda.TestTool/Amazon.Lambda.TestTool.csproj
> +	  <None Include="$(OutputPath)Amazon.Lambda.RuntimeSupport.dll" Pack="true" PackagePath="content" Visible="false" />
i still need to test end to end with aspire poc if any more (lambda core dlls) are needed or anything else

2024-12-17 18:39 UTC, philasmar commented on Tools/LambdaTestTool-v2/src/Amazon.Lambda.TestTool/Amazon.Lambda.TestTool.csproj
> +	  <None Include="$(OutputPath)Amazon.Lambda.RuntimeSupport.dll" Pack="true" PackagePath="content" Visible="false" />
I'm assuming this is only adding the current target framework (net8.0) version of RuntimeSupport. I believe we need to add all targets of Runtimesupport. @normj is my assumption correct?

2024-12-17 18:40 UTC, philasmar reviewed
I'm assuming this is only adding the current target framework (net8.0) version of RuntimeSupport. I believe we need to add all targets of Runtimesupport. @normj is my assumption correct?

2024-12-17 18:43 UTC, gcbeattyAWS commented on Tools/LambdaTestTool-v2/src/Amazon.Lambda.TestTool/Amazon.Lambda.TestTool.csproj
> +	  <None Include="$(OutputPath)Amazon.Lambda.RuntimeSupport.dll" Pack="true" PackagePath="content" Visible="false" />
i remember he mentioned when he updated the test tool v2 something about to not worry about the other versions. but ill let him confirm

2025-01-14 07:34 UTC, normj commented on Tools/LambdaTestTool-v2/src/Amazon.Lambda.TestTool/Amazon.Lambda.TestTool.csproj
> +	  <None Include="$(OutputPath)Amazon.Lambda.RuntimeSupport.dll" Pack="true" PackagePath="content" Visible="false" />
We will need to distribute each target framework for Lambda RuntimeSupport. That is how things work in Lambda. I think what you are thinking about is I meant with test tool v2 we only need to ship one version of the test tool NuGet package unlike the current v1 version were we ship separate versions of the package for each target framework. In the end we will have a single V2 test tool NuGet package with one .NET tool which is the Lambda emulator and then separate content folders for each version of RuntimeSupport with RuntimeSupport's dependencies.

2025-01-14 15:39 UTC, gcbeattyAWS commented on Tools/LambdaTestTool-v2/src/Amazon.Lambda.TestTool/Amazon.Lambda.TestTool.csproj
> +	  <None Include="$(OutputPath)Amazon.Lambda.RuntimeSupport.dll" Pack="true" PackagePath="content" Visible="false" />
Ahh ok let me make that change. thanks for the detailed explanation

2025-01-14 20:12 UTC, gcbeattyAWS commented on Tools/LambdaTestTool-v2/src/Amazon.Lambda.TestTool/Amazon.Lambda.TestTool.csproj
> +    <RuntimeSupportFramework Include="net5.0;net6.0;net8.0;netstandard2.0" />
we havent updated runtime support in this branch to add .net9.0 which is why i havent added it here

2025-01-14 20:13 UTC, gcbeattyAWS commented on Tools/LambdaTestTool-v2/src/Amazon.Lambda.TestTool/Amazon.Lambda.TestTool.csproj
> +	  <None Include="$(OutputPath)Amazon.Lambda.RuntimeSupport.dll" Pack="true" PackagePath="content" Visible="false" />
ive updated it now, where each runtime support target version has its own folder with a dll in the content folder of the test tool

2025-01-14 20:13 UTC, gcbeattyAWS commented on Tools/LambdaTestTool-v2/src/Amazon.Lambda.TestTool/Amazon.Lambda.TestTool.csproj
> +	  <None Include="$(OutputPath)Amazon.Lambda.RuntimeSupport.dll" Pack="true" PackagePath="content" Visible="false" />
ive also updated the screenshot in the description

2025-01-14 20:14 UTC, gcbeattyAWS commented on Tools/LambdaTestTool-v2/src/Amazon.Lambda.TestTool/Amazon.Lambda.TestTool.csproj
> +      <Content Include="$(MSBuildThisFileDirectory)..\..\..\..\Libraries\src\Amazon.Lambda.RuntimeSupport\bin\$(Configuration)\%(RuntimeSupportFramework.Identity)\Amazon.Lambda.RuntimeSupport.dll">
i havent been able to test end to end yet with aspire to see if any dependency dlls are also needed for runtime support. Unless someone happens to know off the top of their head if we need any other dlls?

2025-01-14 20:20 UTC, gcbeattyAWS commented on Tools/LambdaTestTool-v2/src/Amazon.Lambda.TestTool/Amazon.Lambda.TestTool.csproj
> +      <Content Include="$(MSBuildThisFileDirectory)..\..\..\..\Libraries\src\Amazon.Lambda.RuntimeSupport\bin\$(Configuration)\%(RuntimeSupportFramework.Identity)\Amazon.Lambda.RuntimeSupport.dll">
possibly lambda core is needed too but im yet to confirm

2025-01-14 22:11 UTC, normj reviewed
Instead of adding the project reference and manually copying the dll I wonder if we should have a customer target that runs before the `Pack` target and run some script that does a `dotnet publish` for each supported target. And then copy the output publish folder to a content folder in the test package for each target framework. That would cover all of the dependencies and would be the same as who the Runtime assembly and its dependencies are copied into the image.

Plus having the project dependency even though we don't use it is annoying because it means we have to keep building RuntimeSupport and its dependencies as part of our dev loop.

2025-01-15 17:25 UTC, gcbeattyAWS commented
> Instead of adding the project reference and manually copying the dll I wonder if we should have a customer target that runs before the `Pack` target and run some script that does a `dotnet publish` for each supported target. And then copy the output publish folder to a content folder in the test package for each target framework. That would cover all of the dependencies and would be the same as who the Runtime assembly and its dependencies are copied into the image.
> 
> Plus having the project dependency even though we don't use it is annoying because it means we have to keep building RuntimeSupport and its dependencies as part of our dev loop.

i have updated the latest logic to do this

2025-01-15 17:26 UTC, gcbeattyAWS commented on Tools/LambdaTestTool-v2/src/Amazon.Lambda.TestTool/Amazon.Lambda.TestTool.csproj
> +	  <None Include="$(OutputPath)Amazon.Lambda.RuntimeSupport.dll" Pack="true" PackagePath="content" Visible="false" />
I've updated the latest logic to now use dotnet publish and copy everything in the publish folder to the content folder. and i have updated the screenshot in the description

2025-01-17 15:59 UTC, philasmar requested changes

2025-01-17 15:59 UTC, philasmar commented on Tools/LambdaTestTool-v2/src/Amazon.Lambda.TestTool/Amazon.Lambda.TestTool.csproj
> +      <TargetFrameworks Include="netstandard2.0;net5.0;net6.0;net8.0" />
You should drop net5 and add net9

2025-01-17 15:59 UTC, philasmar commented on Tools/LambdaTestTool-v2/src/Amazon.Lambda.TestTool/Amazon.Lambda.TestTool.csproj
> +    <Message Importance="high" Text="Publishing Amazon.Lambda.RuntimeSupport project..." />
nit: message is a bit misleading or non descriptive

2025-01-17 15:59 UTC, philasmar commented on Tools/LambdaTestTool-v2/tests/Amazon.Lambda.TestTool.UnitTests/PackagingTests.cs
> +    {
update frameworks here too

2025-01-17 16:48 UTC, gcbeattyAWS commented on Tools/LambdaTestTool-v2/src/Amazon.Lambda.TestTool/Amazon.Lambda.TestTool.csproj
> +    <Message Importance="high" Text="Publishing Amazon.Lambda.RuntimeSupport project..." />
yea i iwll remove the message

2025-01-22 18:25 UTC, gcbeattyAWS commented on Tools/LambdaTestTool-v2/src/Amazon.Lambda.TestTool/Amazon.Lambda.TestTool.csproj
> +      <TargetFrameworks Include="netstandard2.0;net5.0;net6.0;net8.0" />
ive updated this in my local branch but waiting on https://github.com/aws/aws-lambda-dotnet/pull/1937/files to be merged first

2025-01-22 19:22 UTC, gcbeattyAWS commented on Tools/LambdaTestTool-v2/src/Amazon.Lambda.TestTool/Amazon.Lambda.TestTool.csproj
> +      <TargetFrameworks Include="netstandard2.0;net5.0;net6.0;net8.0" />
fixed

2025-01-22 19:22 UTC, gcbeattyAWS commented on Tools/LambdaTestTool-v2/src/Amazon.Lambda.TestTool/Amazon.Lambda.TestTool.csproj
> +    <Message Importance="high" Text="Publishing Amazon.Lambda.RuntimeSupport project..." />
fixed

2025-01-22 19:22 UTC, gcbeattyAWS commented on Tools/LambdaTestTool-v2/tests/Amazon.Lambda.TestTool.UnitTests/PackagingTests.cs
> +    {
done

2025-01-23 18:27 UTC, gcbeattyAWS commented on Tools/LambdaTestTool-v2/src/Amazon.Lambda.TestTool/Amazon.Lambda.TestTool.csproj
> +	  <None Include="$(OutputPath)Amazon.Lambda.RuntimeSupport.dll" Pack="true" PackagePath="content" Visible="false" />
i tested this end to end and this works now

2025-01-24 01:26 UTC, normj requested changes

2025-01-24 01:26 UTC, normj commented on Tools/LambdaTestTool-v2/src/Amazon.Lambda.TestTool/Amazon.Lambda.TestTool.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk.Web">
Because of our unorthodox packaging of the assemblies I'm getting a lot of `NU5100` warnings. Can you add `<NoWarn>NU5100</NoWarn>` to the `PropertyGroup`.

2025-01-24 01:26 UTC, normj commented on Tools/LambdaTestTool-v2/src/Amazon.Lambda.TestTool/Amazon.Lambda.TestTool.csproj
> +        <PackagePath>content\%(TargetFrameworks.Identity)</PackagePath>
Can you change `content\%(TargetFrameworks.Identity)` to `content\Amazon.Lambda.RuntimeSupport\%(TargetFrameworks.Identity)` to give some name spacing to the content here.

2025-01-24 01:26 UTC, normj commented on Tools/LambdaTestTool-v2/tests/Amazon.Lambda.TestTool.UnitTests/PackagingTests.cs
> +    {
Would be great if instead of having this hardcoded list if you read the `TargetFrameworks` from the Amazon.Lambda.RuntimeSupport project file. That way we don't have to update this every time we add a new supported version.

You can skip .NET Standard 2.0.

2025-01-24 01:26 UTC, normj commented on Tools/LambdaTestTool-v2/src/Amazon.Lambda.TestTool/Amazon.Lambda.TestTool.csproj
> +      <None Include="$(MSBuildThisFileDirectory)..\..\..\..\Libraries\src\Amazon.Lambda.RuntimeSupport\bin\$(Configuration)\%(TargetFrameworks.Identity)\publish\**\*.*">
It would be great if we could skip `netstandard2.0` because it doesn't make any sense in this context. The `netstandard2.0` target is for class libraries not executables.

2025-01-24 16:24 UTC, gcbeattyAWS commented on Tools/LambdaTestTool-v2/src/Amazon.Lambda.TestTool/Amazon.Lambda.TestTool.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk.Web">
done

2025-01-24 16:24 UTC, gcbeattyAWS commented on Tools/LambdaTestTool-v2/src/Amazon.Lambda.TestTool/Amazon.Lambda.TestTool.csproj
> +        <PackagePath>content\%(TargetFrameworks.Identity)</PackagePath>
done

2025-01-24 16:25 UTC, gcbeattyAWS commented on Tools/LambdaTestTool-v2/src/Amazon.Lambda.TestTool/Amazon.Lambda.TestTool.csproj
> +      <None Include="$(MSBuildThisFileDirectory)..\..\..\..\Libraries\src\Amazon.Lambda.RuntimeSupport\bin\$(Configuration)\%(TargetFrameworks.Identity)\publish\**\*.*">
ive updated the logic in the csproj and the unit test to dynamically get the targetframeworks and also skip netstandard2.0

2025-01-24 17:37 UTC, normj approved these changes
Nice job. Some impressive MSBuild work here.

2025-01-27 16:53 UTC, philasmar approved these changes

2025-01-27 17:17 UTC, merged